In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/insurance2.csv')
df

   age  height  weight  premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40     NaN     110    60000
4   45  157.48      85    70000

In [3]:
mean_height=df['height'].mean()
mean_height

np.float64(165.1)

In [4]:
df.height = df.height.fillna(mean_height)
df

   age  height  weight  premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40  165.10     110    60000
4   45  157.48      85    70000

In [6]:
from sklearn  import linear_model
reg=linear_model.LinearRegression()

In [7]:
reg.fit(df[['age','height','weight']],df['premium'])

LinearRegression()

In [8]:
reg.coef_

array([2150.26052416, -248.45851574,  312.65291961])

In [9]:
reg.intercept_

np.float64(-16827.01315482489)

In [10]:
reg.predict([[27,167.56,60]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([18357.48727691])