In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/titanic.csv')
df

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df.drop(['PassengerId','Name','Pclass','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

      Sex   Age     Fare  Survived
0    male  22.0   7.2500         0
1  female  38.0  71.2833         1
2  female  26.0   7.9250         1
3  female  35.0  53.1000         1
4    male  35.0   8.0500         0

In [ ]:
inputs=df.drop('Survived',axis='columns')
target=df.Survived

In [ ]:
# inputs.Sex=inputs.Sex.map({'male':0,'female':1})

In [ ]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

      Sex   Age     Fare  female   male
0    male  22.0   7.2500   False   True
1  female  38.0  71.2833    True  False
2  female  26.0   7.9250    True  False

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

    Age     Fare  female
0  22.0   7.2500   False
1  38.0  71.2833    True
2  26.0   7.9250    True

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

    Age     Fare  female
0  22.0   7.2500   False
1  38.0  71.2833    True
2  26.0   7.9250    True
3  35.0  53.1000    True
4  35.0   8.0500   False

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.7910447761194029

In [ ]:
X_test[0:10]

           Age      Fare  female
268  58.000000  153.4625    True
351  29.699118   35.0000   False
20   35.000000   26.0000   False
272  41.000000   19.5000    True
1    38.000000   71.2833    True
172   1.000000   11.1333    True
762  20.000000    7.2292   False
834  18.000000    8.3000   False
113  20.000000    9.8250    True
62   45.000000   83.4750   False

In [ ]:
y_test[0:10]

268    1
351    0
20     0
272    1
1      1
172    1
762    1
834    0
113    0
62     0
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
model.predict_proba(X_test[:10])

array([[4.25118085e-04, 9.99574882e-01],
       [9.11779808e-01, 8.82201919e-02],
       [9.24220937e-01, 7.57790626e-02],
       [2.68853994e-01, 7.31146006e-01],
       [1.05973131e-01, 8.94026869e-01],
       [1.31105301e-01, 8.68894699e-01],
       [9.07236626e-01, 9.27633739e-02],
       [9.03521012e-01, 9.64789880e-02],
       [2.15594717e-01, 7.84405283e-01],
       [7.20169892e-01, 2.79830108e-01]])

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.816     , 0.8       , 0.768     , 0.78225806, 0.72580645])